export enum NB {
  MinusOne = -1,
  Zero = 0,
  ZeroPointOne = 0.1,
  ZeroPointSeventeen = 0.17,
  ZeroPointThirtyFour = 0.34,
  ZeroPointThree = 0.3,
  ZeroPointTwentyOne = 0.21,
  ZeroPointTwentyFive = 0.25,
  ZeroPointFive = 0.5,
  ZeroPointFiftyOne = 0.51,
  ZeroPointSixtyEight = 0.68,
  ZeroSeventyFive = 0.75,
  ZeroPointEightyFive = 0.85,
  One = 1,
  OnePointTwo = 1.2,
  OnePointFive = 1.5,
  Two = 2,
  TwoPointOne = 2.1,
  TwoPointFive = 2.5,
  Three = 3,
  Four = 4,
  Five = 5,
  Six = 6,
  Seven = 7,
  Eight = 8,
  Ten = 10,
  Eleven = 11,
  Twelve = 12,
  Fourteen = 14,
  Fifteen = 15,
  Sixteen = 16,
  Seventeen = 17,
  Twenty = 20,
  TwentyFour = 24,
  TwentyFive = 25,
  Forty = 40,
  FortyTwo = 42,
  Fifty = 50,
  Sixty = 60,
  SixtyTwo = 62,
  SixtyFour = 64,
  SeventyFour = 74,
  Eighty = 80,
  OneHundred = 100,
  OneHundredEightTwo = 182,
  TwoHundred = 200,
  TwoHundredThree = 203,
  TwoHundredFifty = 250,
  TwoHundredFiftyFive = 255,
  ThreeHundred = 300,
  FourHundred = 400,
  FourHundredOne = 401,
  FourHundredNinety = 490,
  FiveHundred = 500,
  FiveHundredOne = 501,
  SixHundred = 600,
  SixHundredFifty = 650,
  NineHundred = 900,
  OneThousand = 1000,
  TenThousand = 10000,
  }

export enum KEY {
  shift = 'Shift',
}

export const HIDE_DIALOG = 'hideDialog';

export enum TOOL {
  rectangle,
  brush,
  pen,
  colorApplicator,
}

export enum BRUSH {
  chalk = 'chalk',
  smear = 'smear',
  rough = 'rough',
  smooth = 'smooth',
  bubbly = 'bubbly',
}

export const EMPTY_STRING = '';
