/* Icons taken from noto-emoji:
 * https://github.com/googlefonts/noto-emoji
 */

export const svgFileLocation: string[] = [
  '../assets/stamps/emoji_u1f32d.svg',
  '../assets/stamps/emoji_u1f354.svg',
  '../assets/stamps/emoji_u1f35f.svg',
  '../assets/stamps/emoji_u1f36b.svg',
  '../assets/stamps/emoji_u1f36d.svg',
  '../assets/stamps/emoji_u1f42d.svg',
  '../assets/stamps/emoji_u1f436.svg',
  '../assets/stamps/emoji_u1f43a.svg',
  '../assets/stamps/emoji_u1f43b.svg',
  '../assets/stamps/emoji_u1f43c.svg',
  '../assets/stamps/emoji_u1f440.svg',
  '../assets/stamps/emoji_u1f44c.svg',
  '../assets/stamps/emoji_u1f44d.svg',
  '../assets/stamps/emoji_u1f4a4.svg',
  '../assets/stamps/emoji_u1f4a5.svg',
  '../assets/stamps/emoji_u1f4a9.svg',
  '../assets/stamps/emoji_u1f4af.svg',
  '../assets/stamps/emoji_u1f602.svg',
  '../assets/stamps/emoji_u1f606.svg',
  '../assets/stamps/emoji_u1f609.svg',
  '../assets/stamps/emoji_u1f60a.svg',
  '../assets/stamps/emoji_u1f60b.svg',
  '../assets/stamps/emoji_u1f60d.svg',
  '../assets/stamps/emoji_u1f60e.svg',
  '../assets/stamps/emoji_u1f60f.svg',
  '../assets/stamps/emoji_u1f611.svg',
  '../assets/stamps/emoji_u1f61a.svg',
  '../assets/stamps/emoji_u1f61e.svg',
  '../assets/stamps/emoji_u1f620.svg',
  '../assets/stamps/emoji_u1f622.svg',
  '../assets/stamps/emoji_u1f62d.svg',
  '../assets/stamps/emoji_u1f62e.svg',
  '../assets/stamps/emoji_u1f630.svg',
  '../assets/stamps/emoji_u1f631.svg',
  '../assets/stamps/emoji_u1f634.svg',
  '../assets/stamps/emoji_u1f641.svg',
  '../assets/stamps/emoji_u1f642.svg',
  '../assets/stamps/emoji_u1f64a.svg',
  '../assets/stamps/emoji_u1f6ab.svg',
  '../assets/stamps/emoji_u1f92f.svg',
];
